apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # The port your application listens on
      targetPort: 80  # The container port
      nodePort: 30080 # The external port to access (range: 30000-32767)
  type: NodePort
